### ISSUE TITLE
Documentation on installation

### ISSUE THREAD

**Issue by officialasit** [ivov/nodemaker#8]
Hi,

Is there a documentation on how to use this tool along with n8n from scratch ?
Thanks

**Comment by ivov** [comment]
We'll be updating the docs very soon. I'll keep you posted!

/cc @erin2722

**Comment by officialasit** [comment]
Thanks @ivov 
looking forward to create some custom nodes with this tool.

**Comment by ivov** [comment]
Docs will be finalized next week, but most of them are already available at:

https://github.com/MLH-Fellowship/nodemaker
